name: Dependent Jobs Example

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: echo "Running build..."

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: echo "Running tests..."

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy step
        run: echo "Deploying application..."
